In [21]:
import numpy as np
x = np.array([1,2,3])
tr = np.dot(x.x)
print(tr) 

AttributeError: 'numpy.ndarray' object has no attribute 'x'

In [3]:
import numpy as np
a = np.array([[27,4,24],[3,33,0],[0,33,29],[14,0,17]])
b = np.array([[1.65,2.08,1.62,1.5],[1.65,2.08,1.62,1.5],[1.65,2.08,1.62,1.5]])
c = np.multiply(a,b.T)
print(c)

[[ 44.55   6.6   39.6 ]
 [  6.24  68.64   0.  ]
 [  0.    53.46  46.98]
 [ 21.     0.    25.5 ]]


In [ ]:
import numpy as np
a = np.array([[27,4,24],[3,33,0],[0,33,29],[14,0,17]])
b = np.multiply(a,a)
c = np.multiply(a,b.T)
print(c)

In [9]:
import numpy as np
a = np.array([[27,4,24],[3,33,0],[0,33,29],[14,0,17]])
b = np.sum(np.multiply(a,a),axis = 0)
c = np.sqrt(np.sum(np.multiply(a,a),axis = 0))
d = a/c
print(b)
print(c)
print(d.T)

[ 934 2194 1706]
[ 30.56141358  46.84015371  41.30375286]
[[ 0.88346699  0.098163    0.          0.45809399]
 [ 0.08539682  0.70452373  0.70452373  0.        ]
 [ 0.581061    0.          0.70211538  0.41158488]]


In [11]:
import numpy as np
Doc1 = np.array([0.88, 0.10, 0, 0.46])
Doc2 = np.array([0.09, 0.71,  0.71, 0])
Doc3 = np.array([0.58, 0, 0.7, 0.41])
print("Doc1xDoc2:",Doc1* Doc2)
print("Doc2xDoc3:",Doc2* Doc3)
print("Doc1xDoc3:",Doc1* Doc3)
print("************************")
print("Doc1xDoc2:",np.sum(Doc1* Doc2))
print("Doc2xDoc3:",np.sum(Doc2* Doc3))
print("Doc1xDoc3:",np.sum(Doc1* Doc3))

Doc1xDoc2: [ 0.0792  0.071   0.      0.    ]
Doc2xDoc3: [ 0.0522  0.      0.497   0.    ]
Doc1xDoc3: [ 0.5104  0.      0.      0.1886]
************************
Doc1xDoc2: 0.1502
Doc2xDoc3: 0.5492
Doc1xDoc3: 0.699


In [3]:
import numpy as np
A = np.array([[1,3,4],[2,5,8]])
m,n = A.shape
print(m,n)

2 3


In [4]:
import numpy as np
A = np.random.randn(3,2)
print(A)

[[ 0.61407212  1.33566559]
 [ 0.39285896  0.26775394]
 [-1.42785213 -1.17145392]]
